### ISSUE TITLE
Warnung beim leihsystem

### ISSUE THREAD

**Issue by seeker20** [lantreff/dotlan_project#26]
Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /var/ 

dies scheint da oben.

**Comment by seeker20** [comment]
Fehler liegt in der vorhergehende SQL befehl: Unknown column 'Array' in 'where clause'

**Comment by seeker20** [comment]
Das problem ist, dass event_id einen Array ist.
wenn man drüber sagt, dass $event_id = $event_id[0]; eingibt, ist dies behoben.

**Comment by KnEggE** [comment]
Das Problem ist die Umstellung der Eventid seitens dotlan, diese hatte ich im Projekt bereits in der functions.php umgestellt.

$event_id = $EVENT->next darf nicht mehr in den einzelnen Modulen verwendet werden. Dies hatte ich leider nicht bei allen   Modulen nach der Umstellung umgesetzt.

$event_id wird in der /admin/Projekt/functions.php definiert und kanm in allen Modulen verwendet werden.



Bitte schließt nicht nur mit einem Kommentar ein issue ab.. Sin ist es ein issue ja im Quelltext zu beheben, bei eventueller vorheriger Diskusion und Abstimmung mit dem Modul Ersteller. ;-)
